### ISSUE TITLE
Peer to Peer review from TEAM-45-THE-HELIUMS

### ISSUE THREAD

**Issue by euqueme** [KingsleyMcSimon/TicTacToe-Project#2]
Hello, Erick, these are our inputs on your project:

- Use this [inspiration](https://github.com/othneildrew/Best-README-Template) to build a more descriptive README file.

- The method names and commits messages are very descriptive so good job!

-  def initialize(p1="x") you never use the parameter.

- Leave a space between each method definition

- Don't repeat yourself in the draw_board method keep it DRY.

Keep up the good work!

**Comment by Oitur** [comment]
So, I've gotten rid of the unused parameter, and used linter to approach the spaces problem. I'll ask my partner to do the readme file and the draw_board method will be upgraded in milestone 3 of the project.

**Comment by Oitur** [comment]
Ok, so the README will be fixed in next milestone, the code is now DRY and all other suggestions have been addressed. Closing issue
