### ISSUE TITLE
Peer to Peer review from TEAM-45-THE-HELIUMS #2

### ISSUE THREAD

**Issue by euqueme** [KingsleyMcSimon/TicTacToe-Project#6]
Hello, Erick Congratulations on finishing this project here are our reviews:

- (optional) Maybe you can ask in the beginning the name of the players so if someone wins print the name of the player who won

- instead of "You win" use "You won" with a name it would be for instance: "Maria wins"

- When theres no more space in the board you can print "Game over" or "it's a tie" or "Do you wanna continue playing"

- (optional) let the player choose if they want X or O

Keep up the good work!

**Comment by Oitur** [comment]
All issues have been addressed, except for the continue playing part, which will be addressed in the fourth milestone. Closing issue
