### ISSUE TITLE
Peer to peer code review from Team-45-the-heliums

### ISSUE THREAD

**Issue by euqueme** [KingsleyMcSimon/TicTacToe-Project#8]
Hello Erick so far very good work,  

We only have one suggestion: address the double readme already noticed by the TSE and be more descriptive in the gameplay maybe add some screenshots to it.

That's all, keep up the good work.

**Comment by Oitur** [comment]
Double readme has been fixed. Instead of screenshots, I've added game instructions with the actual output.
